---
title: "PL Project Draft"
author: "Matthew Palagyi"
date: '2022-08-13'
output: pdf_document
---

*Needed Libraries*
```{r message=FALSE, warning=FALSE, results='hide'}
library(knitr)
library(tinytex)
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(sf)
library(readxl)
library(spdep)
library(caret)
library(ckanr)
library(grid)
library(gridExtra)
library(knitr)
library(kableExtra)
library(tidycensus)
library(scales)
library(ggpubr)
library(ggcorrplot)
library(coefplot)
library(rsample)
library(ggpubr)
library(jtools)
library(gridExtra)
library(car)
library(zoo)
library(tmap)
library(gifski)
library(gganimate)
library(ggthemes)
library(ggmap)
library(seg)
library(viridis)
library(ggthemes)
library(seg)
```

# PL Project Draft

```{r include = TRUE, message=FALSE, warning=FALSE, results='hide'}
#reading in already created excel csv

excel_table1 <- read_excel("./Arsenal Premier League Finishes and Results_1.xlsx")

excel_table2 <- read_excel("./Arsenal Premier League Finishes and Results_2.xlsx")
  

```

```{r include = TRUE, message=FALSE, warning=FALSE, results='hide'}
#creating new tibble from the skeleton of excel csvs

Arsenal_PL_Data <- tribble(
  ~Season, ~Ars_Finish, ~Ars_Pts, ~Champion, ~Champion_Pts, ~Fourth, ~Fourth_Pts, ~Pts_vs_Top6, ~Pts_vs_Remains, ~Home_Pts, ~Home_GS, ~Home_GA, ~Away_Pts, ~Away_GS, ~Away_GA,
  "12/13", 4, 73, "Man. United", 89, "Arsenal", 73, 7, 66, 38, 47, 23, 35, 25, 14,
  "13/14", 4, 79, "Man. City", 86, "Arsenal", 79, 12, 67, 44, 36, 11, 35, 25, 14,
  "14/15", 3, 75, "Chelsea", 87, "Man. United", 70, 11, 64, 41, 41, 14, 34, 30, 22,
  "15/16", 2, 71, "Leicester", 81, "Man. City", 66, 16, 55, 40, 31, 11, 34, 31, 35,
  "16/17", 5, 75, "Chelsea", 95, "Liverpool", 76, 9, 66, 45, 39, 16, 30, 38, 28,
  "17/18", 6, 63, "Man. City", 100, "Liverpool", 75, 6, 57, 47, 54, 20, 16, 20, 31,
  "18/19", 5, 70, "Man. City", 98, "Spurs", 71, 12, 58, 45, 42, 16, 25, 31, 35,
  "19/20", 8, 56, "Liverpool", 99, "Chelsea", 66, 10, 46, 36, 36, 24, 20, 20, 24,
  "20/21", 8, 61, "Man. City", 86, "Chelsea", 68, 17, 44, 28, 24, 21, 34, 31, 18,
  "21/22", 5, 69, "Man. City", 93, "Spurs", 71, 9, 68, 41, 35, 17, 28, 26, 31)

ManCity_16.17 <- tribble(~Season, ~Finish, ~Pts, ~After_12, ~After_21, ~After_30, ~After_38, ~Pts_vs_Top6, ~Pts_vs_Remains,
  "16/17", 3, 78, 27, 42, 58, 78, 10, 68)
```
























